apply plugin: 'com.palantir.gradle-plugin-testing'
apply plugin: 'java-gradle-plugin'
apply plugin: 'java-test-fixtures'
apply plugin: 'com.palantir.external-publish-jar'
apply plugin: 'groovy'

dependencies {
    compileOnly gradleApi()

    implementation 'com.palantir.gradle.failure-reports:gradle-failure-reports-exceptions'
    implementation 'com.palantir.gradle.utils:platform'
    api 'com.palantir.gradle.utils:circleci-artifacts'
    api 'com.palantir.gradle.utils:environment-variables'

    testImplementation gradleApi()
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

gradlePlugin {
    // do not add new task to publish to plugins.gradle.org
    automatedPublishing = false
}

gradleTestUtils {
    configurationCacheEnabled = true
}

tasks.named('test', Test) {
    systemProperty 'projectVersion', project.version

    // Publish to maven local so that tests can directly import BetterExec
    dependsOn tasks.publishToMavenLocal
}
