apply plugin: 'com.palantir.gradle-plugin-testing'
apply plugin: 'java-gradle-plugin'
apply plugin: 'java-test-fixtures'
apply plugin: 'com.palantir.external-publish-jar'
apply plugin: 'groovy'

dependencies {
    compileOnly gradleApi()

    implementation 'com.palantir.gradle.failure-reports:gradle-failure-reports-exceptions'
    implementation 'com.palantir.gradle.utils:platform'
    implementation 'com.palantir.gradle.utils:circleci-artifacts'
    implementation 'com.palantir.gradle.utils:environment-variables'

    testImplementation gradleApi()
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

gradlePlugin {
    // do not add new task to publish to plugins.gradle.org
    automatedPublishing = false
}

gradleTestUtils {
    gradleVersions = ['8.14.3']
    configurationCacheEnabled = true
}

// Publish to maven local so that tests can directly import BetterExec
tasks.test.dependsOn tasks.publishToMavenLocal

test {
    systemProperty 'projectVersion', project.version
}
